services:
  - type: web
    name: runprogress
    runtime: node
    buildCommand: cd server && npm install && cd .. && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
